version: 2

sources:
  - name: customer_engagement
    database: customer-engagement-dbt
    schema: customer_engagement
    tables:
      - name: customers
      - name: events

models:
  - name: stg_customers
    description: "Cleaned customer data"
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: stg_events
    description: "Cleaned event tracking data"
    columns:
      - name: event_id
        tests: [not_null, unique]

